CREATE DATABASE QUANLIBANHANG 

USE QUANLIBANHANG

CREATE TABLE KHACHHANG(
	MAKH char(4) PRIMARY KEY,
	HOTEN varchar(40),
	DIACHI varchar(50),
	SDT varchar(20),
	NGSINH smalldatetime,
	DOANHSO money,
	NGDK smalldatetime,
);

CREATE TABLE NHANVIEN(
	MANV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	NGVL smalldatetime,
	SDT varchar(20),
);

CREATE TABLE SANPHAM(
	MASP char(4) PRIMARY KEY,
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar(20),
	GIA money,
);

CREATE TABLE HOADON(
	SOHD int PRIMARY KEY,
	NGHD smalldatetime,
	MAKH char(4) REFERENCES KHACHHANG(MAKH),
	MANV char(4) REFERENCES NHANVIEN(MANV),
	TRIGIA money,
);

CREATE TABLE CTHD(
	SOHD int REFERENCES HOADON(SOHD),
	MASP char(4) REFERENCES SANPHAM(MASP),
	SL int CHECK (SL >= 1),
	PRIMARY KEY (SOHD, MASP),
);

ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100)

ALTER TABLE SANPHAM
DROP COLUMN GHICHU

ALTER TABLE SANPHAM ADD
CONSTRAINT CHECK (GIA > 500)

