-- Tạo database quản lí giáo vụ
CREATE DATABASE QUANLIGIAOVU

USE QUANLIGIAOVU

-- Tạo các quan hệ trong database
CREATE TABLE HOCVIEN(
	 MAHV char(5) PRIMARY KEY,
	 HO varchar(40),
	 TEN varchar(10),
	 NGSINH smalldatetime,
	 GIOITINH varchar(3),
	 NOISINH varchar(40),
	 MALOP char(4),
);

CREATE TABLE KHOA(
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4),
);

CREATE TABLE MONHOC(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4) REFERENCES KHOA(MAKHOA),
);

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
	MAMH_TRUOC VARCHAR(10) REFERENCES MONHOC(MAMH),
	PRIMARY KEY (MAMH, MAMH_TRUOC),
);

CREATE TABLE GIAOVIEN(
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4) REFERENCES KHOA(MAKHOA),
);

CREATE TABLE LOP(
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5) REFERENCES HOCVIEN(MAHV),
	SISO TINYINT,
	MAGVCN CHAR(4) REFERENCES GIAOVIEN(MAGV),
);

CREATE TABLE GIANGDAY(
	MALOP CHAR(3) REFERENCES LOP(MALOP),
	MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
	MAGV CHAR(4) REFERENCES GIAOVIEN(MAGV),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH),
);

CREATE TABLE KETQUATHI(
	MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
	MAHV CHAR(5) REFERENCES HOCVIEN(MAHV),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	PRIMARY KEY(MAHV, MAMH, LANTHI),
);

ALTER TABLE KHOA ADD
CONSTRAINT FK_TGK_GV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

-- 3. Thuộc tính của GIOITINH chỉ có giá trị là "Nam" hoặc "Nữ".
ALTER TABLE HOCVIEN ADD
CONSTRAINT CK_GT_HV CHECK (GIOITINH IN ('Nam', 'Nu'))

ALTER TABLE GIAOVIEN ADD
CONSTRAINT CK_GT_GV CHECK (GIOITINH IN ('Nam', 'Nu'))

-- 4. Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).
ALTER TABLE KETQUATHI ADD 
CONSTRAINT CK_DIEM CHECK (
	DIEM BETWEEN 0 AND 10 AND
	LEN(SUBSTRING(CAST(DIEM AS VARCHAR), CHARINDEX('.', DIEM) + 1, 1000)) >= 2
)

-- 5. Kết quả thi là “Dat” nếu điểm từ 5 đến 10  và “Khong dat” nếu điểm nhỏ hơn 5.
ALTER TABLE KETQUATHI ADD 
CONSTRAINT CK_KQUA CHECK (KQUA = IIF(DIEM BETWEEN 5 AND 10, 'Dat', 'Khong dat'))

-- 6. Học viên thi một môn tối đa 3 lần.
ALTER TABLE KETQUATHI ADD
CONSTRAINT CK_SOLANTHI CHECK (LANTHI <= 3)

-- 7. Học kì chỉ có giá trị từ 1 đến 3.
ALTER TABLE GIANGDAY ADD
CONSTRAINT CK_HOCKY CHECK (HOCKY BETWEEN 1 AND 3)

-- 8. Học vị của giáo viên chỉ có thể là "CN", "KS", "ThS", "TS", "PTS".
ALTER TABLE GIAOVIEN ADD
CONSTRAINT CK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'ThS', 'TS', 'PTS'))


